CREATE TABLE card (
                      id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      card_type   VARCHAR(20)  NOT NULL,
                      card_name   VARCHAR(255) NOT NULL,
                      passcode    VARCHAR(20)  NOT NULL,
                      card_status VARCHAR(20)  NOT NULL,
                      description TEXT,
                      image_url   VARCHAR(500),
                      created_at  TIMESTAMP    NOT NULL,
                      updated_at  TIMESTAMP    NOT NULL,
                      CONSTRAINT uk_card_passcode UNIQUE (passcode)
);

CREATE TABLE monster_card (
                              card_id BIGINT NOT NULL PRIMARY KEY,
                              attribute VARCHAR(20) NOT NULL,
                              race      VARCHAR(30) NOT NULL,
                              level     INT NOT NULL,
                              attack    INT NOT NULL,
                              defense   INT NOT NULL,
                              CONSTRAINT fk_monster_card_card FOREIGN KEY (card_id) REFERENCES card (id)
);

CREATE TABLE monster_card_type (
                                   monster_card_id BIGINT NOT NULL,
                                   type            VARCHAR(20) NOT NULL,
                                   CONSTRAINT fk_monster_card_type_monster_card FOREIGN KEY (monster_card_id) REFERENCES monster_card (card_id)
);
